name: CI

on:
  push:
  release:
    types: [published]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        # The versions should contain (at least) the lowest requirement
        #    and a version that is more up to date.
        toit-version: [ v2.0.0-alpha.189, latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v5

      - uses: toitlang/action-setup@v1
        with:
          toit-version: ${{ matrix.toit-version }}

      - name: Test
        run: |
          make test
